### ISSUE TITLE
Add 'locate me' function to the map

### ISSUE THREAD

**Issue by Burtchen** [refugeehackathon/mapfix#18]
Use case: I just got out of city hall and need to find a hotspot/playground/whatevs.

**Comment by miku** [comment]
Example for geolocation I did yesterday: https://gist.github.com/miku/f006124c9c212d14a37b, basically:

```
...
if (navigator.geolocation) {
   navigator.geolocation.getCurrentPosition(success, error);
} else {
  error('not supported');
}
...
```
