### ISSUE TITLE
Find relevant categories, that are also features in OSM

### ISSUE THREAD

**Issue by miku** [refugeehackathon/mapfix#4]
http://wiki.openstreetmap.org/wiki/Map_Features defines a lot of things to mark. Following might be interesting for us:
- http://wiki.openstreetmap.org/wiki/Map_Features#Amenity
- http://wiki.openstreetmap.org/wiki/Map_Features#Office

**Comment by donSchoe** [comment]
assigning this to the design department ;-)

_assign_
